#!/bin/bash

# global bash_profile
if [[ -f /etc/profile ]]; then
    source /etc/profile
fi

# env variables
export PATH=~/.opt/bin:~/.local/bin:$PATH
export ROFI_PASS_BACKEND=wtype

# local bash_profile
if [[ -f ~/.bash_profile.local ]]; then
    source ~/.bash_profile.local
fi

# bashrc
if [[ -f ~/.bashrc ]]; then
    source ~/.bashrc
fi

# vim: set sw=4:
