#!/bin/bash


# Command prompt colors
str2int(){
 echo $1 | sha1sum | sed 's/[^0-9]*//g' | cut -c1-6 | xargs -I{} expr {} % $2 + 1
}
USERCOLOR=$(str2int `whoami` 229)
HOSTCOLOR=$(str2int `hostname | cut -d . -f1 | cut -d - -f1` 229)

# Command prompt
PS1="\[\e[1;38;5;${USERCOLOR}m\]\u\[\e[1;38;5;${HOSTCOLOR}m\]@\h:\w$\[\e[0m\] "


# completion
if [[ -f /usr/share/bash-completion/bash_completion ]]; then
    source /usr/share/bash-completion/bash_completion
fi
if [[ -t 1 ]]; then
    bind '"\e[Z": menu-complete'            # shift-tab
    bind '"\e\e[Z": menu-complete-backward' # alt-shift-tab
    bind 'set show-all-if-ambiguous on'
    bind 'set page-completions off'
fi


# line wrap when terminal is resized
shopt -s checkwinsize


# environment variables
if [[ $(command -v vim) ]]; then
    export EDITOR=vim
    alias vimdiff='vim -d'
fi
if [[ $(command -v nvim) ]]; then
    export MANPAGER="nvim -c 'set ft=man' -"
    alias vimdiff='nvim -d'
    export EDITOR=nvim
fi
if [[ $(command -v vimpager) ]]; then
    export PAGER="vimpager"
fi
if [[ $(command -v waterfox) ]]; then
    export BROWSER=waterfox
elif [[ $(command -v firefox) ]]; then
    export BROWSER=firefox
fi
export SYSTEMD_PAGER=''


# alias
alias ls='ls --color=auto --time-style="+%F %H:%M"'
alias duh='du -h --max-depth=1 | sort -h'


# Set terminal title
case $TERM in
xterm*|vte*|rxvt*)
  if [ -e /etc/sysconfig/bash-prompt-xterm ]; then
      PROMPT_COMMAND=/etc/sysconfig/bash-prompt-xterm
  elif [ "${VTE_VERSION:-0}" -ge 3405 ]; then
      PROMPT_COMMAND="__vte_prompt_command"
  else
      PROMPT_COMMAND='printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/~}"'
  fi
  ;;
screen*)
  if [ -e /etc/sysconfig/bash-prompt-screen ]; then
      PROMPT_COMMAND=/etc/sysconfig/bash-prompt-screen
  else
      PROMPT_COMMAND='printf "\033k%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/~}"'
  fi
  ;;
*)
  [ -e /etc/sysconfig/bash-prompt-default ] && PROMPT_COMMAND=/etc/sysconfig/bash-prompt-default
  ;;
esac

# vim: set sw=4:
