config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  f_config:
    src: config/waybar/config
    dst: ~/.config/waybar/config
  f_style.css:
    src: config/waybar/style.css
    dst: ~/.config/waybar/style.css
  f_alacritty.yml:
    src: config/alacritty.yml
    dst: ~/.config/alacritty.yml
  f_ansible.cfg:
    src: ansible.cfg
    dst: ~/.ansible.cfg
  f_flake8:
    src: config/flake8
    dst: ~/.config/flake8
  f_config.ini:
    src: config/gammastep/config.ini
    dst: ~/.config/gammastep/config.ini
  f_git_config:
    src: config/git/config
    dst: ~/.config/git/config
  f_kanshi_config:
    src: config/kanshi/config
    dst: ~/.config/kanshi/config
  f_npmrc:
    src: npmrc
    dst: ~/.npmrc
  f_pylintrc:
    src: config/pylintrc
    dst: ~/.config/pylintrc
  f_rifle.conf:
    src: config/ranger/rifle.conf
    dst: ~/.config/ranger/rifle.conf
  f_rofi-pass_config:
    src: config/rofi-pass/config
    dst: ~/.config/rofi-pass/config
  f_yamllint_config:
    src: config/yamllint/config
    dst: ~/.config/yamllint/config
  f_sway_config:
    src: config/sway/config
    dst: ~/.config/sway/config
  f_plugins.vim:
    src: config/nvim/plugins.vim
    dst: ~/.config/nvim/plugins.vim
    actions:
    - vim-plug-install
    - vim-plug
    - vimpager
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
    actions:
    - vimbackup
  f_help.vim:
    src: config/nvim/ftplugin/help.vim
    dst: ~/.config/nvim/ftplugin/help.vim
  f_html.vim:
    src: config/nvim/ftplugin/html.vim
    dst: ~/.config/nvim/ftplugin/html.vim
  f_javascript.vim:
    src: config/nvim/ftplugin/javascript.vim
    dst: ~/.config/nvim/ftplugin/javascript.vim
    actions:
    - vue.vim
  f_json.vim:
    src: config/nvim/ftplugin/json.vim
    dst: ~/.config/nvim/ftplugin/json.vim
  f_python.vim:
    src: config/nvim/ftplugin/python.vim
    dst: ~/.config/nvim/ftplugin/python.vim
  f_rst.vim:
    src: config/nvim/ftplugin/rst.vim
    dst: ~/.config/nvim/ftplugin/rst.vim
  f_tex.vim:
    src: config/nvim/ftplugin/tex.vim
    dst: ~/.config/nvim/ftplugin/tex.vim
  f_typescript.vim:
    src: config/nvim/ftplugin/typescript.vim
    dst: ~/.config/nvim/ftplugin/typescript.vim
  f_xml.vim:
    src: config/nvim/ftplugin/xml.vim
    dst: ~/.config/nvim/ftplugin/xml.vim
  f_sshterm.sh:
    src: opt/scripts/sshterm.sh
    dst: ~/.opt/scripts/sshterm.sh
  f_venv.sh:
    src: opt/scripts/venv.sh
    dst: ~/.opt/scripts/venv.sh
  f_showclipboard.sh:
    src: opt/scripts/showclipboard.sh
    dst: ~/.opt/scripts/showclipboard.sh
  f_paswitchsink.sh:
    src: opt/scripts/paswitchsink.sh
    dst: ~/.opt/scripts/paswitchsink.sh
  f_paswitchprofile.sh:
    src: opt/scripts/paswitchprofile.sh
    dst: ~/.opt/scripts/paswitchprofile.sh
  f_kanshi-current:
    src: opt/bin/kanshi-current
    dst: ~/.opt/bin/kanshi-current
    chmod: '755'
  f_man.vim:
    src: config/nvim/ftplugin/man.vim
    dst: ~/.config/nvim/ftplugin/man.vim
  f_git.vim:
    src: config/nvim/after/ftplugin/git.vim
    dst: ~/.config/nvim/after/ftplugin/git.vim
  f_markdown.vim:
    src: config/nvim/ftplugin/markdown.vim
    dst: ~/.config/nvim/ftplugin/markdown.vim
  f_jabra-hsp-profile.sh:
    src: opt/scripts/jabra-hsp-profile.sh
    dst: ~/.opt/scripts/jabra-hsp-profile.sh
    chmod: '777'
actions:
  vue.vim: ln -s ~/.config/nvim/ftplugin/javascript.vim ~/.config/nvim/ftplugin/vue.vim
  vim-plug-install: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim-plug: nvim -u NORC '+source ~/.config/nvim/init.vim' +PlugUpdate +UpdateRemotePlugins
    +qall
  vimpager: \[ -h ~/.opt/bin/vimpager \] || (mkdir -p ~/.opt/bin/ && ln -s ~/.config/nvim/plugged/vimpager/vimpager
    ~/.opt/bin/)
  vimbackup: mkdir -p ~/.vimbackup
profiles:
  default:
    dotfiles:
    - f_bashrc
    - f_bash_profile
    - f_config
    - f_style.css
    - f_alacritty.yml
    - f_ansible.cfg
    - f_flake8
    - f_config.ini
    - f_git_config
    - f_kanshi_config
    - f_npmrc
    - f_pylintrc
    - f_rifle.conf
    - f_rofi-pass_config
    - f_yamllint_config
    - f_sway_config
    - f_init.vim
    - f_plugins.vim
    - f_help.vim
    - f_html.vim
    - f_javascript.vim
    - f_json.vim
    - f_python.vim
    - f_rst.vim
    - f_tex.vim
    - f_typescript.vim
    - f_xml.vim
    - f_sshterm.sh
    - f_venv.sh
    - f_showclipboard.sh
    - f_paswitchsink.sh
    - f_paswitchprofile.sh
    - f_kanshi-current
    - f_man.vim
    - f_git.vim
    - f_markdown.vim
    - f_jabra-hsp-profile.sh
