[lint]
select = ["ALL"]
ignore = ["COM812", "ANN", "Q000", "D102", "EM101", "PLR2004", "S101", "D212", "TD002", "TD003", "D200"]
preview = true
explicit-preview-rules = true
extend-select = ["E302"]

[lint.pycodestyle]
max-line-length = 79
max-doc-length = 72

[lint.pydocstyle]
convention = "pep257"
